# Generated by Django 5.2.5 on 2025-09-02 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_branch_outlet_rename_branch_asset_outlet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='build',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='dvr',
            new_name='cpu',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='local_ip',
            new_name='disk',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='device_model',
            new_name='model',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='device_type',
            new_name='power_rating',
        ),
        migrations.RenameField(
            model_name='asset',
            old_name='hdd_total_space',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='internet_speed',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='power_adapter',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='total_display',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='version',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='video_input',
        ),
        migrations.AddField(
            model_name='asset',
            name='date_purchase',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='gpon_sn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='gpu',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='hostname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='item',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='memory',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='operating_system',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='wifi_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(choices=[('retail', 'Retail'), ('it', 'IT')], max_length=10),
        ),
        migrations.AlterField(
            model_name='asset',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='outlet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.outlet'),
        ),
    ]
