# Generated by Django 5.2.5 on 2025-09-02 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_build_asset_brand_rename_dvr_asset_cpu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='dvr',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
