# Generated by Django 5.2.5 on 2025-09-04 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_asset_dvr'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outlet',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='outlet',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.CreateModel(
            name='ITAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=120, null=True)),
                ('model', models.CharField(blank=True, max_length=120, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True)),
                ('hostname', models.CharField(blank=True, max_length=120, null=True)),
                ('operating_system', models.CharField(blank=True, max_length=120, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=50, null=True)),
                ('cpu', models.CharField(blank=True, max_length=120, null=True)),
                ('memory', models.CharField(blank=True, max_length=120, null=True)),
                ('gpu', models.CharField(blank=True, max_length=120, null=True)),
                ('disk', models.CharField(blank=True, max_length=120, null=True)),
                ('wifi_type', models.CharField(blank=True, max_length=50, null=True)),
                ('gpon_sn', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(blank=True, max_length=120, null=True)),
                ('date_purchase', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.outlet')),
            ],
            options={
                'ordering': ['outlet__name', 'item'],
            },
        ),
        migrations.CreateModel(
            name='RetailAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=120, null=True)),
                ('model', models.CharField(blank=True, max_length=120, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=120, null=True)),
                ('date_purchase', models.DateField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.outlet')),
            ],
            options={
                'ordering': ['outlet__name', 'item'],
            },
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
    ]
