# Generated by Django 5.2.5 on 2025-09-08 15:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_outlet_options_alter_outlet_name_itasset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPUAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('assigned', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('motherboard_model', models.CharField(max_length=100)),
                ('operating_system', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=100)),
                ('memory', models.CharField(max_length=100)),
                ('gpu', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=50)),
                ('mac_address', models.CharField(max_length=50)),
                ('disk', models.CharField(max_length=100)),
                ('disk_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='itasset',
            options={},
        ),
        migrations.AlterModelOptions(
            name='outlet',
            options={},
        ),
        migrations.AlterModelOptions(
            name='retailasset',
            options={},
        ),
        migrations.AddField(
            model_name='itasset',
            name='asset_type',
            field=models.CharField(choices=[('cpu', 'CPU'), ('cctv', 'CCTV')], default='cpu', max_length=10),
        ),
        migrations.AddField(
            model_name='itasset',
            name='network',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='retailasset',
            name='power_input',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='retailasset',
            name='sn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='brand',
            field=models.CharField(default='Unknown', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itasset',
            name='cpu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='date_purchase',
            field=models.DateField(default='1970-01-01'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itasset',
            name='disk',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='gpon_sn',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='gpu',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='hostname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='ip_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='mac_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='memory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='operating_system',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='serial_number',
            field=models.CharField(default='UNKNOWN', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itasset',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='wifi_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='outlet',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='retailasset',
            name='brand',
            field=models.CharField(default='UNKNOWN', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retailasset',
            name='date_purchase',
            field=models.DateField(default=datetime.date(2023, 1, 1)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retailasset',
            name='item',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='retailasset',
            name='serial_number',
            field=models.CharField(default='UNKNOWN', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NetworkAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=100)),
                ('brand', models.CharField(default='Unknown', max_length=100, null=True)),
                ('model', models.CharField(max_length=100)),
                ('power_rating', models.CharField(max_length=100)),
                ('wifi_type', models.CharField(max_length=100)),
                ('gpon_sn', models.CharField(max_length=100)),
                ('sn', models.CharField(max_length=100)),
                ('date_purchase', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=100)),
                ('outlet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.outlet')),
            ],
        ),
    ]
