# Generated by Django 5.2.5 on 2025-09-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_cpuasset_alter_itasset_options_alter_outlet_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='retailasset',
            name='serial_number',
        ),
        migrations.AlterField(
            model_name='retailasset',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='retailasset',
            name='date_purchase',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='retailasset',
            name='model',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retailasset',
            name='power_input',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retailasset',
            name='remark',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='retailasset',
            name='sn',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='retailasset',
            name='status',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
