# Generated by Django 5.2.5 on 2025-09-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_retailasset_serial_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itasset',
            name='date_purchase',
            field=models.DateField(blank=True, null=True),
        ),
    ]
