# Generated by Django 5.2.5 on 2025-09-09 17:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_itasset_date_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itasset',
            name='date_purchase',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
            preserve_default=False,
        ),
    ]
