# Generated by Django 5.2.5 on 2025-09-10 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_itasset_device_type_itasset_hdd_total_space_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itasset',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
