# Generated by Django 5.2.5 on 2025-09-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_itasset_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itasset',
            name='serial_number',
            field=models.CharField(max_length=100),
        ),
    ]
