# Generated by Django 5.2.5 on 2025-09-19 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_itasset_serial_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('description', models.TextField()),
                ('technician', models.CharField(max_length=100)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.retailasset')),
            ],
        ),
        migrations.DeleteModel(
            name='CPUAsset',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='device_type',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='hdd_total_space',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='hybrid',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='local_ip',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='nic_speed',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='power_adapter',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='total_channel',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='version',
        ),
        migrations.RemoveField(
            model_name='itasset',
            name='video_input',
        ),
    ]
