# Generated by Django 5.2.5 on 2025-09-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_service_delete_cpuasset_remove_itasset_device_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPUAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('assigned', models.CharField(max_length=100)),
                ('hostname', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=100)),
                ('motherboard_model', models.CharField(max_length=100)),
                ('operating_system', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=100)),
                ('memory', models.CharField(max_length=100)),
                ('gpu', models.CharField(max_length=100)),
                ('ip_address', models.CharField(max_length=50)),
                ('mac_address', models.CharField(max_length=50)),
                ('disk', models.CharField(max_length=100)),
                ('disk_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='itasset',
            name='device_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='hdd_total_space',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='hybrid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='local_ip',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='nic_speed',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='power_adapter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='total_channel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itasset',
            name='video_input',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
