# Generated by Django 5.2.5 on 2025-09-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_cpuasset_itasset_device_type_itasset_hdd_total_space_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CPUAsset',
        ),
        migrations.AddField(
            model_name='itasset',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='retailasset',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
