# Generated by Django 5.2.5 on 2025-10-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_delete_cpuasset_itasset_active_retailasset_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itasset',
            name='date_purchase',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='status',
            field=models.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Under Maintenance', 'Under Maintenance'), ('Draft', 'Draft')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='networkasset',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Under Maintenance', 'Under Maintenance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='retailasset',
            name='date_purchase',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retailasset',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='retailasset',
            name='sn',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='retailasset',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Under Maintenance', 'Under Maintenance'), ('Draft', 'Draft')], default='Draft', max_length=100),
        ),
    ]
