# Generated by Django 5.2.5 on 2025-10-09 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_itasset_date_purchase_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itasset',
            options={'ordering': ['-created_at'], 'verbose_name': 'IT Asset', 'verbose_name_plural': 'IT Assets'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-service_date']},
        ),
        migrations.AddField(
            model_name='itasset',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=-2001),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itasset',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='asset_type',
            field=models.CharField(choices=[('cpu', 'CPU'), ('cctv', 'CCTV'), ('network', 'Network Device'), ('printer', 'Printer'), ('other', 'Other')], default='cpu', max_length=10),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='hybrid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Under Maintenance', 'Under Maintenance'), ('Draft', 'Draft')], default='Draft', max_length=100),
        ),
    ]
