# Generated by Django 5.2.5 on 2025-10-09 06:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_itasset_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itasset',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
