# Generated by Django 5.2.5 on 2025-10-09 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_itasset_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='itasset',
            name='build',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Build'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='device_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Device Model'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='firmware_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Firmware Version'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='hardware_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Hardware Version'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='onvif_client_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ONVIF Client Version'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='onvif_server_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ONVIF Server Version'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='p2p_qr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='P2P QR'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='port',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Port'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='security_baseline_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Security Baseline Version'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='software_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Software Version'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='system_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='System Version'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='web_version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Web Version'),
        ),
        migrations.AddField(
            model_name='itasset',
            name='wip',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='WIP'),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='device_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Device Type'),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='hdd_total_space',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='HDD Total Space'),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='hybrid',
            field=models.BooleanField(default=False, verbose_name='Hybrid'),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='power_adapter',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Power Adapter/Cord'),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='total_channel',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Total Channel'),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='version',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Version'),
        ),
        migrations.AlterField(
            model_name='itasset',
            name='video_input',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Video Input'),
        ),
    ]
