# Generated by Django 5.2.5 on 2025-10-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_itasset_build_itasset_device_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itasset',
            name='asset_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Asset ID'),
        ),
        migrations.AddField(
            model_name='retailasset',
            name='asset_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Asset ID'),
        ),
    ]
