# Generated by Django 5.2.5 on 2025-10-13 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_itasset_asset_id_retailasset_asset_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='itasset',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Assigned User'),
        ),
        migrations.AddField(
            model_name='retailasset',
            name='user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Assigned User'),
        ),
    ]
