# Generated by Django 5.2.5 on 2025-10-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_itasset_user_retailasset_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itasset',
            name='p2p_qr',
            field=models.ImageField(blank=True, null=True, upload_to='p2p_qr/', verbose_name='P2P QR Code'),
        ),
    ]
