# Generated by Django 5.2.5 on 2025-11-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_itasset_p2p_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='itasset',
            name='allocation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='retailasset',
            name='allocation',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
